# -*- coding: utf-8 -*-
"""Untitled127.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqP65CIlMxaOX53gxE1iXsGnP_UH6Ma8
"""

from setuptools import setup, Extension
from pybind11.setup_helpers import Pybind11Extension, build_ext

ext_modules = [
    Pybind11Extension(
        "calculus",
        ["calculus.cpp"],
        cxx_std=11,
    ),
]

setup(
    name="calculus",
    version="1.0.0",
    author="Your Name",
    description="Calculus library with C++ backend",
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
)
